Vault Specialized Container, Test, and Repo files
testcontainers/testcontainers-java-module-vault pull request #1
Opened 2017-06-07 15:32 UTC by mikeoswald

This PR includes the initial codebase for the Vault specialized container. I have added a test class and README that includes an example of usage.

Resolves https://github.com/testcontainers/testcontainers-java/issues/331

2017-06-07 19:27 UTC, bsideup requested changes

2017-06-07 19:27 UTC, bsideup commented on .travis.yml
> +before_install:
these lines are only needed for testing of "the latest and greatest" Docker. I think you can remove the whole "before_install" block

2017-06-07 19:27 UTC, bsideup commented on README.md
> +<!--[![Build Status](https://travis-ci.org/testcontainers/testcontainers-java.svg?branch=master)](https://travis-ci.org/testcontainers/testcontainers-java)-->
this badge is for the main project (testcontainers-java). We should use repo-specific badge here

2017-06-07 19:27 UTC, bsideup commented on README.md
> +Running Vault in your Junit tests is easily done with an @TestRule such as the following:
minor: It's just `@Rule`, not `@TestRule` :)

2017-06-07 19:27 UTC, bsideup commented on README.md
> +    public static VaultContainer vaultContainer = new VaultContainer<>("vault:0.7.0")
Maybe we should provide the default constructor with pre-set vault version like we already do for PostgreSQL/MySQL/others?

2017-06-07 19:27 UTC, bsideup commented on pom.xml
> +            <url>https://api.bintray.com/maven/richnorth/maven/org.testcontainers.vault/;publish=1</url>
@rnorth was it agreed?

2017-06-07 19:27 UTC, bsideup commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        getWaitStrategy().waitUntilReady(this);
you shouldn't call it directly. Use `containerIsStarted` instead

2017-06-07 19:27 UTC, bsideup commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        secretsMap.forEach((path, secrets) -> {
please run a single exec command inside a container instead of a command per secret, it might affect the performance

2017-06-07 19:27 UTC, bsideup commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        return array;
or just `return new String[] { "vault", "write", path }` :)

2017-06-07 19:27 UTC, bsideup commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        Stream.of(remainingSecrets).forEach(s -> list.add(s));
please use classic for loop, Stream is not needed here

2017-06-07 19:27 UTC, bsideup commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        if (secretsMap.containsKey(path)) {
`secretsMap.computeIfAbsent(path, ArrayList::new).addAll(list)`

2017-06-07 19:27 UTC, bsideup commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +    private boolean preloadSecret = false;
do we really need this flag? Can't we just assume that if secretsMap is not empty then we need to preload secrets? :)

2017-06-15 01:34 UTC, mikeoswald commented
@bsideup I've done my best to address your review comments. Can you take a look at the changes? Thanks

2017-06-15 01:34 UTC, mikeoswald commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +    private boolean preloadSecret = false;
👍 removed it.

2017-06-15 01:35 UTC, mikeoswald commented on README.md
> +    public static VaultContainer vaultContainer = new VaultContainer<>("vault:0.7.0")
Update made.

2017-06-15 01:35 UTC, mikeoswald commented on README.md
> +Running Vault in your Junit tests is easily done with an @TestRule such as the following:
done.

2017-06-15 01:35 UTC, mikeoswald commented on README.md
> +<!--[![Build Status](https://travis-ci.org/testcontainers/testcontainers-java.svg?branch=master)](https://travis-ci.org/testcontainers/testcontainers-java)-->
done.

2017-06-15 01:35 UTC, mikeoswald commented on .travis.yml
> +before_install:
done.

2017-06-15 01:36 UTC, mikeoswald commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        getWaitStrategy().waitUntilReady(this);
done.

2017-06-15 01:36 UTC, mikeoswald commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        secretsMap.forEach((path, secrets) -> {
I have reworked the method to now run a single exec command even if there are multiple secrets or paths.

2017-06-15 01:37 UTC, mikeoswald commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        return array;
reworked, thanks

2017-06-15 01:37 UTC, mikeoswald commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        Stream.of(remainingSecrets).forEach(s -> list.add(s));
done.

2017-06-15 01:38 UTC, mikeoswald commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        if (secretsMap.containsKey(path)) {
Couldn't quite get this exact command to work, but have reworked it and is cleaner now.

2017-06-15 01:39 UTC, mikeoswald commented on pom.xml
> +            <url>https://api.bintray.com/maven/richnorth/maven/org.testcontainers.vault/;publish=1</url>
@rnorth let me know if I need to modify this.

2017-06-23 09:28 UTC, kiview requested changes

2017-06-23 09:28 UTC, kiview commented on pom.xml
> +            <url>https://api.bintray.com/maven/richnorth/maven/org.testcontainers.vault/;publish=1</url>
Maybe it's best to remove this part for the first release an we'll talk about possible artifact management in the future.

2017-06-23 09:28 UTC, kiview commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +            withEnv("VAULT_ADDR", "http://0.0.0.0:8200");
Port 8200 is used in multiple parts of the code, maybe have this in a constant?

2017-06-23 09:28 UTC, kiview commented
I've added some small comments, the rest looks good to me.

2017-06-24 02:19 UTC, mikeoswald commented
@kiview thanks for the review. I have updated the PR per your comments.

2017-06-26 14:27 UTC, mikeoswald commented
I just pushed one last change, I removed the setPortBindings if they don't specify a port to bind on. That way if people want to link to this container in tests they shouldn't need to expose ports. Just a cleaner approach. 

Thanks, I think this is ready for merge.

2017-06-26 15:48 UTC, kiview requested changes
Just a tiny code style change, sorry for nitpicking, I think this happened when extracting the constant. I will merge afterwards 👍

2017-06-26 15:48 UTC, kiview commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +    private static final String VAULT_PORT="8200";
Please surround binary operators with two spaces (I assume it's a refactoring error here ;)).

2017-06-26 15:48 UTC, kiview commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +            withEnv("VAULT_ADDR", "http://0.0.0.0:"+VAULT_PORT);
Missing spaces here as well

2017-06-26 15:48 UTC, kiview commented on src/main/java/org/testcontainers/vault/VaultContainer.java
> +        setPortBindings(Arrays.asList(vaultPort+":"+VAULT_PORT));
Missing spaces

2017-06-26 19:17 UTC, kiview approved these changes

2017-06-26 19:19 UTC, merged